token = 'vk1.a.0p7AfGU1rLe6DWQabUEsFmSUNOVoz-onQqEhJD21w5HZN_cEWWTiywA90BVCU7pG7HQjQKfzGsP2gltoY2wMOikszohoLsyRBGnzg1H65Zq5xdQSgJXA42z1aOnPP4KqqBKUOAZphdvUeW4iBqaBACtyuQ7IhlKBaQfGO4YSfwiWKmXWQaevqENK1amZdvjfpve9abZTi3IsvChshvHaQw'
confirmation_token = 'xxxxxxxxxxxx'
username = ''
psw = 'KK8K_AMLuvRk4BJ'
hostname = ''
databasename = ''